--------------------------------------------------------
--  Fichier créé - vendredi-novembre-05-2021   
--------------------------------------------------------
DROP TABLE "SYSTEM"."CLIENT";
DROP TABLE "SYSTEM"."COLLABORATION";
DROP TABLE "SYSTEM"."MATERIELS";
DROP TABLE "SYSTEM"."OFFRES";
DROP TABLE "SYSTEM"."PERSONNEL";
DROP TABLE "SYSTEM"."RESERVATION";
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENT" 
   (	"CIN" NUMBER(20,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ADRESSE_MAIL" VARCHAR2(20 BYTE), 
	"NUM_TEL" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COLLABORATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COLLABORATION" 
   (	"CODE_COLLAB" NUMBER, 
	"COLLABORATEUR" VARCHAR2(20 BYTE), 
	"TYPE_COLLAB" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIELS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MATERIELS" 
   (	"CODE" NUMBER, 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"COULEUR" VARCHAR2(20 BYTE), 
	"CIN" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFRES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."OFFRES" 
   (	"NUM_OFFRE" VARCHAR2(20 BYTE), 
	"DATE_OFFRE" DATE, 
	"DUREE_OFFRE" VARCHAR2(20 BYTE), 
	"CIN" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONNEL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PERSONNEL" 
   (	"CIN" NUMBER(8,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER, 
	"POSTE" VARCHAR2(20 BYTE), 
	"NUM_TEL" NUMBER, 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RESERVATION" 
   (	"CODE_RESERVATION" NUMBER, 
	"DATE_RESERVATION" DATE, 
	"SERVICE" VARCHAR2(20 BYTE), 
	"CIN" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CLIENT
SET DEFINE OFF;
Insert into SYSTEM.CLIENT (CIN,NOM,PRENOM,ADRESSE_MAIL,NUM_TEL) values (7,'k','k','k',4);
Insert into SYSTEM.CLIENT (CIN,NOM,PRENOM,ADRESSE_MAIL,NUM_TEL) values (2,'q','q','q',0);
Insert into SYSTEM.CLIENT (CIN,NOM,PRENOM,ADRESSE_MAIL,NUM_TEL) values (5,'l','m','h',2);
Insert into SYSTEM.CLIENT (CIN,NOM,PRENOM,ADRESSE_MAIL,NUM_TEL) values (26,'abbassi','yosr','aa',26);
REM INSERTING into SYSTEM.COLLABORATION
SET DEFINE OFF;
REM INSERTING into SYSTEM.MATERIELS
SET DEFINE OFF;
REM INSERTING into SYSTEM.OFFRES
SET DEFINE OFF;
REM INSERTING into SYSTEM.PERSONNEL
SET DEFINE OFF;
REM INSERTING into SYSTEM.RESERVATION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CLIENT_PK" ON "SYSTEM"."CLIENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COLLABORATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COLLABORATION_PK" ON "SYSTEM"."COLLABORATION" ("CODE_COLLAB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MATERIELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."MATERIELS_PK" ON "SYSTEM"."MATERIELS" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFRES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."OFFRES_PK" ON "SYSTEM"."OFFRES" ("NUM_OFFRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONNEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PERSONNEL_PK" ON "SYSTEM"."PERSONNEL" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."RESERVATION_PK" ON "SYSTEM"."RESERVATION" ("CODE_RESERVATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("NUM_TEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("ADRESSE_MAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COLLABORATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."COLLABORATION" ADD CONSTRAINT "COLLABORATION_PK" PRIMARY KEY ("CODE_COLLAB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."COLLABORATION" MODIFY ("TYPE_COLLAB" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COLLABORATION" MODIFY ("COLLABORATEUR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."COLLABORATION" MODIFY ("CODE_COLLAB" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIELS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MATERIELS" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATERIELS" ADD CONSTRAINT "MATERIELS_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."MATERIELS" MODIFY ("COULEUR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATERIELS" MODIFY ("CATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MATERIELS" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFFRES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."OFFRES" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."OFFRES" ADD CONSTRAINT "OFFRES_PK" PRIMARY KEY ("NUM_OFFRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."OFFRES" MODIFY ("NUM_OFFRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."OFFRES" MODIFY ("DUREE_OFFRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."OFFRES" MODIFY ("DATE_OFFRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONNEL
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PERSONNEL" ADD CONSTRAINT "PERSONNEL_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("NUM_TEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("POSTE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PERSONNEL" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("CODE_RESERVATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."RESERVATION" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESERVATION" MODIFY ("SERVICE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESERVATION" MODIFY ("DATE_RESERVATION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."RESERVATION" MODIFY ("CODE_RESERVATION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MATERIELS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MATERIELS" ADD CONSTRAINT "MATERIELS_FK1" FOREIGN KEY ("CODE")
	  REFERENCES "SYSTEM"."PERSONNEL" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFFRES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."OFFRES" ADD CONSTRAINT "OFFRES_FK1" FOREIGN KEY ("CIN")
	  REFERENCES "SYSTEM"."PERSONNEL" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RESERVATION" ADD CONSTRAINT "RESERVATION_FK1" FOREIGN KEY ("CIN")
	  REFERENCES "SYSTEM"."CLIENT" ("CIN") ENABLE;
